# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: <%= site_name %>
email: <%= author_email %>
description: > # this means to ignore newlines until "baseurl:"
  <%= site_description %>
baseurl: "" # the subpath of your site, e.g. /blog
url: <%= site_domain %> # the base hostname & protocol for your site
twitter_username: <%= twitter %>
github_username:  <%= git_acc %>

# For non-post pages, ie about, contact
include: ['_pages']

# Build settings
markdown: kramdown

# exclude assets folder
exclude: ["assets/"]
